### PR TITLE
Software Update 2021.05.29.0

### PR DESCRIPTION
**Pull request by shawaj**
Urgent update to miner in relation to chain halt:

- Bumps miner to latest version from helium

### CODE REVIEW

**Comment by ryanteck** [comment]
@shawaj I'm getting quite a few reports that this version of software has introduced bugs. People having units not syncing at all and it does seem to add up.

Can I revert this for now and see what happens?

Normally I leave It for at least a few hours before going from testnet to prod to avoid this as I have found some of Helium's "urgent" updates then break things more and needed to revert back.

**Comment by shawaj** [comment]
I don't think we should revert it unless it can be 100% confirmed that the new miner code is the issue, as it's an urgent update because of the chain halt.

Those few who are having issues on Discord seem more like WiFi issues to me?

**Comment by ryanteck** [comment]
Well I'm getting tickets saying there are.

I can't be certain that this update doesn't have issues because the
complaints indicate it does.

**Comment by shawaj** [comment]
Which tickets? The only ones I've seen from people in Discord seem unrelated.

**Pull request merged**
