### PR TITLE
release: fix balena pushes with random sleep period

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: #299 
- Summary: add random sleep period

**How**

Push fix to production 

**Screenshots**

**References**

#293 

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
@marvinmarnold @KevinWassermann94 seems to have worked better with the random sleep period 

https://github.com/NebraLtd/helium-miner-software/actions/runs/1547183401

**Review by marvinmarnold — APPROVED** [review]

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
fingers crossed 🤞

**Comment by shawaj** [comment]
@marvinmarnold @KevinWassermann94 hip hip hooray 🥳

**Comment by KevinWassermann94** [comment]
Looking great!

**Pull request merged**
