### PR TITLE
Bump to 2021.08.31.1_GA

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Latest miner release

**How**

Bump containers

**References**

### CODE REVIEW

**Comment by shawaj** [comment]
Can be merged once testnet is working nicely

**Comment by KevinWassermann94** [comment]
@shawaj I am fairly certain that there is still an issue on the testnet.

have a look at https://dashboard.balena-cloud.com/devices/fbde142f478761c2a22c5a27bd32bb03/summary - the animal name is wrong and it is not getting any blocks

**Comment by shawaj** [comment]
@KevinWassermann94 can you check again?

**Comment by shawaj** [comment]
Looks good on testnet so merging now

**Pull request merged**
