### PR TITLE
Bump diagnostics and config

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Better handle exceptions in diagnostics
Better handle Bluetooth error messages in config

**How**

Test diag updates in https://github.com/NebraLtd/hm-diag/pull/212 and https://github.com/NebraLtd/hm-diag/pull/217

Test config updates in https://github.com/NebraLtd/hm-config/pull/129

**References**

https://github.com/NebraLtd/hm-diag/pull/212
https://github.com/NebraLtd/hm-diag/pull/217
https://github.com/NebraLtd/hm-diag/issues/204
https://github.com/NebraLtd/hm-config/pull/129

### CODE REVIEW

**Comment by shawaj** [comment]
@marvinmarnold yeah good idea and can bump config and pktfwd too perhaps before then as well if we have fixes in those

**Comment by SebastianMaj** [comment]
@shawaj @marvinmarnold The PR is now merged in with the master branch, API timeout is taken into account and all the other exceptions are caught by #212 

I've been running the timeout changes from #217 and all the exceptions from #212 on my dev miner all day and haven't experienced an error 500 page on diagnostics

**Comment by shawaj** [comment]
Updated the PR details to reflect updates 👌

Guess we can close https://github.com/NebraLtd/hm-diag/issues/204?

**Comment by marvinmarnold** [comment]
> Updated the PR details to reflect updates ok_hand
> 
> Guess we can close [NebraLtd/hm-diag#204](https://github.com/NebraLtd/hm-diag/issues/204)?

We've been inconsistent when we close things. I think we should start closing after QA/testnet but we've mostly been closing after feature PR is merged into service. Thoughts @vpetersson @shawaj.

**Comment by shawaj** [comment]
@marvinmarnold yeah that probably makes sense to do it that way to ensure it's working properly

**Comment by shawaj** [comment]
Although i suppose it is harder to keep track of that way so just need to make sure we reference all the references etc

**Comment by vpetersson** [comment]
@marvinmarnold One solution to this is to use tags. We can for instance have at bot that creates a tag called for instance 'needs-testing-on-testnet' that is automatically added to all PRs. Then we can just go through them and remove them as they are tested.

**Review by marvinmarnold — APPROVED** [review]

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by KevinWassermann94** [comment]
Merging to production blocked by https://github.com/NebraLtd/hm-diag/issues/223

**Comment by KevinWassermann94** [comment]
There seems to be an issue with Removing the Wifi: https://github.com/NebraLtd/hm-config/issues/137
and with the region override (old issue) https://github.com/NebraLtd/hm-pktfwd/issues/67

In my opinion this shouldn't block merging to production as the region override is an old issue and I wouldn't consider the forget Wifi critical and we had some reports before. Considering the improvements on this PR we should push it to production.
What do you think @marvinmarnold @SebastianMaj @shawaj @vpetersson

**Comment by vpetersson** [comment]
Yeah neither of these should block production merge.

**Pull request merged**
