### PR TITLE
fix (production): issue with config container and LED stuck in fast blink

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: https://github.com/NebraLtd/hm-config/issues/188
- Summary: fix issue with config container and LED getting stuck in fast blink

**How**

Run diagnostics thread forever in hm-config

**Screenshots**

**References**

Closes: https://github.com/NebraLtd/hm-config/issues/188
Ref https://github.com/NebraLtd/hm-config/issues/189
Ref #415 

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
Pushed to testnet at 18.45 BST Saturday 9th April 2022

**Comment by shawaj** [comment]
@NebraLtd/developers @NebraLtd/tech-support ?

**Comment by KevinWassermann94** [comment]
@shawaj As per Slack discussion, I couldn't properly test this as the Lora remained true even when stopping the container

**Comment by shawaj** [comment]
> @shawaj As per Slack discussion, I couldn't properly test this as the Lora remained true even when stopping the container

@marvinmarnold is this because if the container is stopped it would never update the packet forwarder file in /var/pktfwd? Is there a way we can make it so that it can update if the container is stopped?

@KevinWassermann94 best way to test is to just remove the concentrator whilst running

**Comment by KevinWassermann94** [comment]
@shawaj The results are even more surprising. I've removed the concentrator while the unit is running and the packet forwarder is still running as usual and no error is thrown.

**Comment by shawaj** [comment]
> @shawaj The results are even more surprising. I've removed the concentrator while the unit is running and the packet forwarder is still running as usual and no error is thrown.

@KevinWassermann94 are you sure the logs in Balena are up to date / live from Balena? I'm wondering whether there is a time delay.

@marvinmarnold worth taking a look at this

**Comment by KevinWassermann94** [comment]
@shawaj Yes, I've double checked and waited like an hour

**Comment by shawaj** [comment]
> @shawaj Yes, I've double checked and waited like an hour

On what device was this? Rock Pi or RasPi?

I get failed to start concentrator and container constantly restarting when I do it

**Comment by shawaj** [comment]
Merging so we can create production images for factory

**Pull request merged**
