### PR TITLE
release(testnet): Improve watchdog

### PR DESCRIPTION
**Pull request by posterzh**
**Issue**

- Link: - https://github.com/NebraLtd/hm-diag/pull/387
- Summary:
Find out the correct connection status to the local gateway and the internet so that watchdog can work reliably.

**How**
- Use dbus interface to the network manager to get the local gateway IP inside the diagnostics container.
- Use ICMP `ping` method to check the connection status to the local gateway(ex, 192.168.0.1) and public IP(8.8.8.8).

**Screenshots**

**References**
- https://github.com/NebraLtd/hm-diag/issues/343
- [icmplib](https://pypi.org/project/icmplib/)

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
Do we still need #467 ?

**Comment by shawaj** [comment]
Oh just realised, that #467 was to push to production and this was to push to master. Sorry didn't look properly 🤦

**Comment by KevinWassermann94** [comment]
@shawaj Zhang has reworked the network watchdog. The reason we didn't push it to production is that there were some issues with the initial version

**Comment by shawaj** [comment]
Cool, can just open a new PR when ready then. Probably easier anyway

**Pull request merged**
