### PR TITLE
release(prod): bump miner to 2021.11.19.0 GA

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Bump to 2021.11.19.0 GA

**How**

Bump up latest GA in hm-miner
https://github.com/NebraLtd/hm-miner/commit/0d4ce82e61a6d2fcb4a029c9d51b6de8c0443e48

**References**

Ref #246
Closes: #251 

https://engineering.helium.com/2021/11/19/blockchain-release-sync-and-snapshot-improvements.html

### CODE REVIEW

**Comment by shawaj** [comment]
Draft until tested on testnet. Pushed to testnet around 3.00 AM UTC 20th November 2021

**Comment by shawaj** [comment]
@KevinWassermann94 if you are happy with this on testnet, we could push to mainnet so that hotspots pull in the latest snapshot to get past the stuck block

**Review by KevinWassermann94 — APPROVED** [review]
Running fine on testnet. I suspect another GA shortly though

**Comment by shawaj** [comment]
> Running fine on testnet. I suspect another GA shortly though

Yep agreed. Also, this probably won't help due to another stuck block. 

Will see how things play out today

**Comment by shawaj** [comment]
Will push this while we test the new GA out on testnet

**Pull request merged**
