### PR TITLE
Bump packet forwarder container commit id  for SX1302 support

### PR DESCRIPTION
**Pull request by robputt**
**Why**

**How**

**References**

### CODE REVIEW

**Comment by robputt** [comment]
See following devices for dev branch

- with SX1302 concentrator - https://dashboard.balena-cloud.com/devices/09d659d8e3647d7b66e0a3db2f318341/summary
- with SX1301 concentrator - https://dashboard.balena-cloud.com/devices/bbb85e3e961fb2ebd0f35c243e734ad0/summary

**Review by marvinmarnold — CHANGES_REQUESTED** [review]
https://github.com/NebraLtd/helium-miner-software/pull/264/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R28 has basically the same version of pktfwd, just missing a trivial bot commit. 

If you want to get this in independently, should bump FIRMWARE_VERSION.

**Comment by shawaj** [comment]
#271 already brought in the sx1302 fixes to testnet

**Comment by shawaj** [comment]
Closing as already in testnet

**Pull request closed without merging**
