### PR TITLE
fix: remove duplicate modem info

### PR DESCRIPTION
**Pull request by shawaj**
It seems that this modem info was accidentally duplicated here at some point. It is only needed in the Quectel modem part

**Issue**

- Link:
- Summary:

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by MuratUrsavas** [comment]
Nope, these are not accidental. They were required for unprivileged `hm-diag`. Not touched without switching completely to `hm-pyhelper`. 

I think it would be better to keep those till we switch.

**Comment by shawaj** [comment]
@MuratUrsavas but they aren't referenced anywhere?

Only the ones in quectel_modem section are used at all?

The ones in device_rpi are never used?

**Comment by MuratUrsavas** [comment]
Well, @pritamghanghas knows it better than me. I was about to remove those references with switching to `hm-pyhelper` but don't think I'd done that.

**Review by pritamghanghas — APPROVED** [review]
yes, change is correct. I don't know when they came into existence but they are redundant.

**Pull request merged**
