### PR TITLE
release (prod): pull in new settings.ini deploy method

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: #272 
- Summary: new deploy strategy

**How**

Implement new deploy strategy

**Screenshots**

**References**

#272 

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Review by KevinWassermann94 — CHANGES_REQUESTED** [review]
Currently seeing Diagnostics have not yet run on all testnet units. Needs resolving first

**Comment by kashifpk** [comment]
> > Currently seeing Diagnostics have not yet run on all testnet units. Needs resolving first
> 
> Hmm very strange indeed. Not sure what could have caused this. @kashifpk any thoughts?

Not sure but I can look that up. Right now I don't see this message on a couple of devices I checked on testnet. @KevinWassermann94 what messages am I looking at?

I see all containers running and the logs only have region override not set errors.

image

The above is from `autumn-grass` on testnet.

**Comment by KevinWassermann94** [comment]
@kashifpk Opening the public device URL you will see the diagnostics page not being able to load

**Comment by kashifpk** [comment]
> @kashifpk Opening the public device URL you will see the diagnostics page not being able to load

Yes just created https://github.com/NebraLtd/helium-miner-software/issues/343 is for addressing this.

**Comment by shawaj** [comment]
@KevinWassermann94 should be working now?

**Comment by KevinWassermann94** [comment]
@shawaj Yes looking good now. I'll quickly go through the QA checks with the team now

**Comment by shawaj** [comment]
How's it looking @NebraLtd/developers @NebraLtd/tech-support ?

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
@NebraLtd/developers any thoughts?

**Comment by vpetersson** [comment]
Reviewing as we speak.

**Review by vpetersson — APPROVED** [review]
Approved, but we need to address https://github.com/NebraLtd/helium-miner-software/issues/345

**Pull request merged**
