### PR TITLE
update: bring in latest packet forwarder for testing

### PR DESCRIPTION
**Pull request by shawaj**
bring in latest packet forwarder for further testing on testnet (has already been tested on light-hotspot-software)

### CODE REVIEW

**Comment by shawaj** [comment]
converted to draft as found a potential issue with sx1302 detection

**Comment by shawaj** [comment]
Should be fixed in https://github.com/NebraLtd/hm-pktfwd/pull/29

**Comment by shawaj** [comment]
Tested with sx1301 and sx1302 in https://github.com/NebraLtd/light-hotspot-software/pull/27

**Comment by shawaj** [comment]
Need to update again once https://github.com/NebraLtd/hm-pktfwd/pull/32 is merged

**Comment by shawaj** [comment]
Updated again now https://github.com/NebraLtd/hm-pktfwd/pull/32 is merged

**Comment by robputt** [comment]
Converted to draft until ready for merge.

**Review by robputt — APPROVED** [review]

**Comment by shawaj** [comment]
@robputt it's ready to be merged whenever

**Review by robputt — APPROVED** [review]

**Pull request merged**
