### PR TITLE
release (prod): adds garbage collection features

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: https://github.com/NebraLtd/hm-miner/pull/69
- Summary: Adds garbage collection features

**How**

Bump miner container

**Screenshots**

**References**

Ref https://github.com/NebraLtd/hm-miner/pull/69
Ref https://github.com/NebraLtd/hm-block-tracker/pull/60

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
Ready for when you finish your tests @KevinWassermann94

**Comment by KevinWassermann94** [comment]
@shawaj Waiting for the GC to kick in. Behaviour seems to be a bit inconsistent so far and only running like once a day

**Comment by KevinWassermann94** [comment]
I got a suspicion here. I am seeing a lot of the units on the Testnet falling behind in sync right now while they are doing their garbage collection. This seems to be in line with the issues RAK is experiencing with hotspots falling behind from time to time

**Comment by KevinWassermann94** [comment]
Just confirming that every single unit(except the 8GB special edition) is falling behind around 20-50 blocks

**Comment by shawaj** [comment]
You think because it's using resources to do the garbage collection and then not catching up?

**Comment by KevinWassermann94** [comment]
That's what I suspect. The garbage collection seems to be very slow and taking it's time, so there will be periods with activity. They should be able to catch up as soon as gc is finished

**Comment by shawaj** [comment]
> That's what I suspect. The garbage collection seems to be very slow and taking it's time, so there will be periods with activity. They should be able to catch up as soon as gc is finished

Just depends how frequently it happens.

I guess the main thing is it won't full up which is better than being full

And 50 blocks behind shouldn't cause it to stop mining

**Comment by KevinWassermann94** [comment]
From my recent observations hotspots seem to not be running properly around 30 blocks behind

**Comment by shawaj** [comment]
> From my recent observations hotspots seem to not be running properly around 30 blocks behind

That's very strange. Normally should be ok out to at least 1k

**Review by KevinWassermann94 — APPROVED** [review]

**Review by marvinmarnold — APPROVED** [review]

**Pull request merged**
