### PR TITLE
release(prod): dbus hotfix, rockpi support, API request fix, and PF fix

### PR DESCRIPTION
**Pull request by marvinmarnold**
**Why**
Trying to fix production issue where miners stuck updating ASAP.

**How**
Including hotfix with other recent changes from today that are low touch but high impact.

An earlier PR into production got [squash-merged](https://github.com/NebraLtd/helium-miner-software/commit/b105077d6abe55972b5e43230d841d6559c1134d). Now a direct merge `production<-master` will cause a conflict.

Production was merged into `marvinmarnold/28/force-restart` (this branch). These changes have also been [pushed to testnet](https://github.com/NebraLtd/helium-miner-software/pull/244). After this is approved, production will need to be back-merged into master by an admin to get the branches in sync again @shawaj @vpetersson .

**References**

- Hotfix for: https://github.com/NebraLtd/helium-miner-software/pull/244
- Closes: https://github.com/NebraLtd/hm-diag/issues/232
- Related to: https://github.com/NebraLtd/hm-diag/issues/222
- Closes: NebraLtd/hm-miner#53
- Closes: NebraLtd/hm-miner#31
- Closes: NebraLtd/hm-block-tracker#52
- Supersedes: #239

### CODE REVIEW

**Review by shawaj — APPROVED** [review]

**Comment by KevinWassermann94** [comment]
Yes lets get this out asap

**Comment by shawaj** [comment]
I'm not sure this really fixes https://github.com/NebraLtd/hm-diag/issues/222

But approving anyway as urgent and we can fix separately.

**Comment by shawaj** [comment]
> Yes lets get this out asap

@KevinWassermann94 can you add approval if you're happy to push?

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by KevinWassermann94** [comment]
@shawaj Had to do the re-approval as it was showing that you approved for both developers and tech-support

**Comment by marvinmarnold** [comment]
> I'm not sure this really fixes NebraLtd/hm-diag#222

@shawaj rereading 222, I see that its intent was specific to wifi. I changed the tag to `relates to`. But I think the rest of the team wants to close 222 because wifi is known to give false negatives.

Also a reminder that I'm not able to merge into prod, so you'll have to pull the trigger.

**Comment by shawaj** [comment]
> > I'm not sure this really fixes [NebraLtd/hm-diag#222](https://github.com/NebraLtd/hm-diag/issues/222)
> 
> @shawaj rereading 222, I see that its intent was specific to wifi. I changed the tag to `relates to`. But I think the rest of the team wants to close 222 because wifi is known to give false negatives.
> 
> Also a reminder that I'm not able to merge into prod, so you'll have to pull the trigger.

My proposition was to decouple the Hotspot production tool from the PF in diagnostics.

What shows in diagnostics does not need to match what we test for in production.

However, we should definitely also be testing for WiFi working in production

**Comment by shawaj** [comment]
@marvinmarnold @KevinWassermann94 do we want to add in 2021.11.19.0 as well?

https://github.com/NebraLtd/hm-miner/commit/0d4ce82e61a6d2fcb4a029c9d51b6de8c0443e48

**Comment by KevinWassermann94** [comment]
@shawaj Let's test the GA on the testnet first. It is not an emergency update and we are already pushing quite a few untested changes

**Comment by shawaj** [comment]
@KevinWassermann94 do we need to push this update urgently now though? Not sure we do having done the dbus thing with the ENV variables?

**Comment by marvinmarnold** [comment]
> My proposition was to decouple the Hotspot production tool from the PF in diagnostics.

HPT is ignoring PF now: https://github.com/NebraLtd/Hotspot-Production-Tool/pull/48
And we'll remove PF entirely with: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/28 and https://github.com/NebraLtd/hm-diag/issues/207

I think @vpetersson  and @KevinWassermann94 [perspective](https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1637338884106000) was that even in hm-diag alone, it does more harm than good to have wifi errors make the diagnostics page show red.

> However, we should definitely also be testing for WiFi working in production

We are not currently.

**Comment by KevinWassermann94** [comment]
@shawaj This is not super urgent anymore. The var fix seems to be working great. The API display error would be nice to be fixed but not an emergency

**Comment by shawaj** [comment]
> > My proposition was to decouple the Hotspot production tool from the PF in diagnostics.
> 
> HPT is ignoring PF now: [NebraLtd/Hotspot-Production-Tool#48](https://github.com/NebraLtd/Hotspot-Production-Tool/pull/48) And we'll remove PF entirely with: [NebraLtd/Hotspot-Production-Tool#28](https://github.com/NebraLtd/Hotspot-Production-Tool/issues/28) and [NebraLtd/hm-diag#207](https://github.com/NebraLtd/hm-diag/issues/207)
> 
> I think @vpetersson and @KevinWassermann94 [perspective](https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1637338884106000) was that even in hm-diag alone, it does more harm than good to have wifi errors make the diagnostics page show red.
> 
> > However, we should definitely also be testing for WiFi working in production
> 
> We are not currently.

There's no point in doing manufacturing tests if we don't test for anything. We need to test WiFi as it's a key feature.

I'm also not convinced it's a firmware issue or that we should show all ok when WiFi isn't working. If we don't want it to show red when there's errors we should remove the "all ok" completely.

Having errors, but still showing all ok on diagnostics seems wrong to me and confusing and obviously incorrect. Basically saying we think broken WiFi is ok which is not the case.

Removing tests for WiFi in manufacturing doesn't seem to be a solution to me either. I can't understand any scenario where that would be a good idea TBH.

**Comment by shawaj** [comment]
> @shawaj This is not super urgent anymore. The var fix seems to be working great. The API display error would be nice to be fixed but not an emergency

@KevinWassermann94 can merge if you think it is worthwhile and the dbus is working ok on testnet?

Alternatively, we could revert to the previous dbus way which is cleaner and just do the ENV variables again to ensure the update goes through smoothly.

Additionally, as a potential temporary fix we could put a version number ENV variable in the dbus-session container as well as the other two to force that container to update each time while balena fix the root cause. Just as an idea

**Comment by KevinWassermann94** [comment]
@shawaj DBUS was working fine on testnet, but we might as well revert that change and do it a bit cleaner with the ENV variables until I receive an update from Balena. We should make sure to update it with each updates for now

**Comment by shawaj** [comment]
> @shawaj DBUS was working fine on testnet, but we might as well revert that change and do it a bit cleaner with the ENV variables until I receive an update from Balena. We should make sure to update it with each updates for now

@KevinWassermann94 @marvinmarnold reverted the dbus local build and instead addded an env var (similar to what we have on miner container) - we should just bump this to something different (doesn't matter what it is) with each update

What do you reckon?

**Comment by KevinWassermann94** [comment]
@shawaj Possibly just set it to the current firmware version to keep it clean and simple?

**Comment by shawaj** [comment]
@KevinWassermann94 like that?

https://github.com/NebraLtd/helium-miner-software/pull/245/files

**Review by KevinWassermann94 — APPROVED** [review]
@shawaj Yes!

**Review by shawaj — APPROVED** [review]

**Pull request merged**
