### PR TITLE
release(prod): Update miner to latest GA 2021.11.21.1

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Update miner to latest GA 2021.11.21.1

**How**

Bump miner container and version numbers

**References**

https://github.com/NebraLtd/hm-miner/commit/31eeca0c7d85eeaa8bac799f943217f5f3541fbd

Closes: #255

### CODE REVIEW

**Comment by shawaj** [comment]
Draft until tested on testnet. 

Pushed to testnet 14.00 UTC 21st November 2021

**Comment by KevinWassermann94** [comment]
@shawaj Let's push this to production as emergency update. Testnet looking good

**Comment by shawaj** [comment]
Ok removed draft status @KevinWassermann94

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
Force merging

**Pull request merged**
