### PR TITLE
Merge master into production

### PR DESCRIPTION
**Pull request by vpetersson**
Merges master into production

### CODE REVIEW

**Comment by vpetersson** [comment]
Don't merge before we've resolved https://github.com/NebraLtd/hm-diag/issues/159

**Comment by shawaj** [comment]
@vpetersson we need to fix the block tracker before we release this too

**Comment by vpetersson** [comment]
Yeah i'm going to cherry-pick in diagnostics only first. Need that for some analysis work.

**Comment by vpetersson** [comment]
Cherry picked in the hm-diag changes only in https://github.com/NebraLtd/helium-miner-software/commit/30433d575a7636da4f9fc3c306e28debb985a653.

**Review by robputt — APPROVED** [review]

**Pull request merged**
