### PR TITLE
fix(diagnostics): expose serial-number

### PR DESCRIPTION
**Pull request by marvinmarnold**
**Why**
As a hotspot owner, I want to be able to access the serial-number.

**How**
Added label `io.balena.features.procfs` to diagnostics.

**References**
- Builds off: https://github.com/NebraLtd/hm-diag/pull/219

### CODE REVIEW

**Comment by shawaj** [comment]
@marvinmarnold all the testnet units seem to have serial number showing in diagnostics page already without this?

Am I missing something?

**Comment by shawaj** [comment]
Also I noticed in the sample here:
https://github.com/NebraLtd/hm-diag/blob/master/docker-compose.yml

That @SebastianMaj has added in an additional ENV variable. 

Do we need that here also?

**Comment by vpetersson** [comment]
@marvinmarnold This should not be needed. I tested this on Testnet:

**RockPi:**
```
$ cat /proc/device-tree/serial-number
34996b0xxxxxx
```

**Raspberry Pi:***
```
$ cat /proc/device-tree/serial-number
0000000063xxxxx
```

That said, we are using the following in hm-diag:

```
    cap_add:
      - SYS_RAWIO
    privileged: true
    labels:
      io.balena.features.sysfs: 1
```

I'm not entirely sure *which* of the following setting exposes `/proc`, but my guess would be either `io.balena.features.sysfs: 1` or `SYS_RAWIO` (but it could really be any of them).

**Comment by marvinmarnold** [comment]
> all the testnet units seem to have serial number showing in diagnostics page already without this?

Interesting. I got stuck on this for a while yesterday because my device didn't have anything inside /proc/device-tree and this fixed it. I'll play around with some other devices today and compare results.

> @SebastianMaj has added in an additional ENV variable. Do we need that here also?

It already has a default value, so it doesn't have to be set. We've [talked about](https://github.com/NebraLtd/hm-diag/pull/217#discussion_r750715341) using this pattern moving forward. We're exposing more and more things through environment variables, and this is just a way to document it better.

**Comment by shawaj** [comment]
@vpetersson @marvinmarnold it worked before without `privileged: true` also

**Comment by shawaj** [comment]
Looks like it's probably SYS_RAWIO:

```
CAP_SYS_RAWIO
              * Perform I/O port operations (iopl(2) and ioperm(2));
              * access /proc/kcore;
              * employ the FIBMAP ioctl(2) operation;
              * open devices for accessing x86 model-specific registers
                (MSRs, see msr(4));
              * update /proc/sys/vm/mmap_min_addr;
              * create memory mappings at addresses below the value
                specified by /proc/sys/vm/mmap_min_addr;
              * map files in /proc/bus/pci;
              * open /dev/mem and /dev/kmem;
              * perform various SCSI device commands;
              * perform certain operations on hpsa(4) and cciss(4)
                devices;
              * perform a range of device-specific operations on other
                devices.
```

**Comment by marvinmarnold** [comment]
I have been working of [this](https://github.com/NebraLtd/helium-miner-software/pull/264) PR/branch and serial number cannot be detected. Using [current](https://github.com/NebraLtd/helium-miner-software/commit/68e306baa1a4ae610927cbf48c78b555eee8b672) master works though. Still unsure of root cause.

**Comment by shawaj** [comment]
> I have been working of [this](https://github.com/NebraLtd/helium-miner-software/pull/264) PR/branch and serial number cannot be detected. Using [current](https://github.com/NebraLtd/helium-miner-software/commit/68e306baa1a4ae610927cbf48c78b555eee8b672) master works though. Still unsure of root cause.

Is this on a RasPi or RockPi you are testing?

**Comment by marvinmarnold** [comment]
> Is this on a RasPi or RockPi you are testing?

RockPi. I have been manually changing to `devices: - /dev/i2c-7:/dev/i2c-7` and doing `balena deploy`. I'm going to work on GPIO stuff and loop back around to this after https://github.com/NebraLtd/helium-miner-software/pull/264 is merged or closed.

**Comment by shawaj** [comment]
@marvinmarnold I've been able to reproduce this too.

I think it's where we have changed from `cat /proc/cpuinfo` to `cat /proc/device-tree/serial-number`

The former returns fine, the latter does not.

With the `privileged: true` it works on testnet but doesn't in the RockPi testnet I set up.

So yeah let's merge this 👍

**Review by shawaj — APPROVED** [review]

**Pull request merged**
