### PR TITLE
Release 2021.11.16.3 to Production

### PR DESCRIPTION
**Pull request by robputt**
**Why**

**How**

**References**

### CODE REVIEW

**Review by KevinWassermann94 — COMMENTED** [review]
needs the snapshotter to be fixed first

**Review by shawaj — APPROVED** [review]

**Comment by KevinWassermann94** [comment]
I am waiting on the first testnet unit to recover. Seeing weird behaviour with units receiving 93.xx% snapshots

**Comment by shawaj** [comment]
> I am waiting on the first testnet unit to recover. Seeing weird behaviour with units receiving 93.xx% snapshots

That's expected as the snapshotter tool is behind. But after that they should get newer ones from the network

@robputt maybe we can manually upload a new snapshot to the bucket or override the use of snapshot tool?

**Comment by shawaj** [comment]
Personally I think we should push it now and fix any issues later. There's no good reason to delay this is super urgent

**Comment by KevinWassermann94** [comment]
@shawaj I would like to see a single unit recover first. I want to prevent the need for a mass reboot. There is something off with the snapshotter

**Comment by shawaj** [comment]
Also @KevinWassermann94 units updated now will get the latest snapshot https://helium-snapshots.nebra.com/latest-snap.json which is 1100020

**Comment by KevinWassermann94** [comment]
They are not

image

**Comment by shawaj** [comment]
> @shawaj I would like to see a single unit recover first. I want to prevent the need for a mass reboot. There is something off with the snapshotter

TBH, in this instance, I strongly disagree. This is emergency+

**Comment by shawaj** [comment]
> They are not
> 
> image

You are cached @KevinWassermann94 do it in incognito

**Comment by KevinWassermann94** [comment]
Doesn't look like I am
image

**Comment by shawaj** [comment]
I can't reproduce that anywhere...

Screenshot_20211117-141259_Chrome

**Comment by KevinWassermann94** [comment]
Still not a single unit was able to load that snapshot after 20 minutes now.

Should we still merge it and then most likely end up in the need for a mass reboot?

**Review by KevinWassermann94 — APPROVED** [review]
FrankenRAK has recovered

**Comment by shawaj** [comment]
> Still not a single unit was able to load that snapshot after 20 minutes now.
> 
> Should we still merge it and then most likely end up in the need for a mass reboot?

Testnet units don't use the same config...

**Comment by shawaj** [comment]
@KevinWassermann94 found the issue.... Staging configs on hm-block-tracker were failing

**Comment by shawaj** [comment]
https://github.com/NebraLtd/hm-block-tracker/actions

Screenshot_20211117-141418_Chrome

**Comment by KevinWassermann94** [comment]
Any chance we can get an even newer snapshot from FrankenRAK?

**Comment by shawaj** [comment]
I've also manually purged cloudflare cache for those URLs just to be safe

**Pull request merged**
