### PR TITLE
Software Update 2021.08.11.2_GA

### PR DESCRIPTION
**Pull request by shawaj**
Bump to ~~2021.08.11.0_GA~~ 2021.08.11.2_GA miner

Can be merged once everything looks good on testnet

### CODE REVIEW

**Comment by KevinWassermann94** [comment]
Do not merge version 2021.08.11.0 - the Helium team will release a fix to this version shortly - https://discord.com/channels/404106811252408320/730418759298318346/875137805121126412

**Comment by shawaj** [comment]
Thanks @KevinWassermann94 👍

**Comment by shawaj** [comment]
Have fixed the issues in hm-config and hm-diag temporarily (they are being rewritten so have not done any major changes).

See notes here https://github.com/NebraLtd/hm-diag/issues/74 and here https://github.com/NebraLtd/hm-config/issues/59

However it looks like helium are reverting this change, at least for now anyway https://github.com/helium/miner/commit/5eb837b5e479cadd091460ac63e70a99a24c126d

Will keep an eye out for the new GA and then update this PR

**Comment by shawaj** [comment]
Running on testnet now

**Pull request merged**
