### PR TITLE
feat: add authentication to diagnostics

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: https://github.com/NebraLtd/hm-diag/issues/39
- Summary: add authentication to diagnostics

**How**

To prepare for future updates and new features, authentication is added to diagnostics page.

*Note that this is a major update and will need thoroughly testing and documenting (for support purposes) whilst on testnet. Customers should be notified of the change via a blog post and email as well after we merge to production.*

**Screenshots**

**References**

https://github.com/NebraLtd/hm-diag/issues/39
https://github.com/NebraLtd/hm-diag/issues/445
https://github.com/NebraLtd/hm-diag/issues/446
https://github.com/NebraLtd/hm-config/pull/225

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
> *Note that this is a major update and will need thoroughly testing and documenting (for support purposes) whilst on testnet. Customers should be notified of the change via a blog post and email as well after we merge to production.*

Just an FYI on this part @ChristopherRush @WayneNebra @KevinWassermann94

**Comment by KevinWassermann94** [comment]
@shawaj I'll get it tested thoroughly today

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by KevinWassermann94** [comment]
@robputt @shawaj We can merge this to testnet right now, correct?

**Comment by shawaj** [comment]
@KevinWassermann94 yep all good

**Comment by Ryan-Goldstein** [comment]
As a suggestion, since the MAC addresses typically appear with colons, and the Nebra Dashboard reports them with colons as well, to avoid users having to copy/paste from the Nebra Dashboard into notepad or something, then deleting the colons, then copying/pasting again into the password field, I'd suggest allowing colons in the password field and stripping them out before determining whether the password is valid.

This would also allow the removal of the "without any colons" wording on the login page.

**Comment by shawaj** [comment]
Not a bad suggestion @Ryan-Goldstein - will see what we can do with @robputt 

Could you put this as an issue on hm-diag repo?

https://github.com/NebraLtd/hm-diag/issues

**Pull request merged**
