### PR TITLE
prod: Bump to 2021.11.17.2 GA

### PR DESCRIPTION
**Pull request by shawaj**
**Why**

Bump to 2021.11.17.2 GA

**How**

Bump up latest GA in hm-miner
https://github.com/NebraLtd/hm-miner/commit/b34655ff2c59a0ad00546d3339321cab336bc030

**References**

Closes: #231 
Ref #230 #229 
https://engineering.helium.com/2021/11/17/blockchain-release-resuming-the-blockchain.html

### CODE REVIEW

**Review by marvinmarnold — APPROVED** [review]

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
Let's leave overnight and wait for approval from @NebraLtd/tech-support cc @KevinWassermann94

**Comment by shawaj** [comment]
@KevinWassermann94 you wanna push to production without testing?

**Comment by shawaj** [comment]
It's on testnet already https://github.com/NebraLtd/helium-miner-software/actions/runs/1474350916

**Comment by KevinWassermann94** [comment]
@shawaj I would consider this one as a critical updateas well. I have noticed a lot of production units stuck in updating anyway.

**Comment by KevinWassermann94** [comment]
Testnet units that have updated are looking fine

**Comment by shawaj** [comment]
> Testnet units that have updated are looking fine

Ok let's push it 👌

The balena outage earlier probably didn't help things..

**Comment by KevinWassermann94** [comment]
@shawaj Definetly. We had a lot of units that have downloaded the update, but single services were stuck on an old version. A reboot has worked on all of them so far

**Pull request merged**
